### ISSUE TITLE
我有一个小白的问题

### ISSUE THREAD

**Issue by shineforwu** [hujunxianligong/Tensorflow-CNN-Tutorial#11]
我想问下这个分类器，分文 训练和 测试2个部分。我先运行了训练（1次），再运行了测试。发现结果都是
···
data\2_82.jpg   鸟 => 汽车
data\2_86.jpg   鸟 => 汽车
data\2_88.jpg   鸟 => 汽车
data\2_90.jpg   鸟 => 汽车
data\2_92.jpg   鸟 => 汽车
data\2_95.jpg   鸟 => 汽车
···
请问是哪边我操作不对了？

I want to ask about this classifier, divided into two parts: training & testing. I ran the training first (1 time) and then run the test. Found that the results are
···
data\2_82.jpg bird => car
data\2_86.jpg bird => car
data\2_88.jpg bird => car
data\2_90.jpg bird => car
data\2_92.jpg bird => car
data\2_95.jpg bird => car
···
Excuse me, where did I do something wrong?

**Comment by hujunxianligong** [comment]
代码提供的是一个未调参的类似LeNet模型，多运行几次还是一样结果么？

**Comment by shineforwu** [comment]
是要多run几次 training后再 run 测试吗？

**Comment by hujunxianligong** [comment]
训练、测试、训练、测试。。。。

shine <notifications@github.com> 于2020年8月14日周五 下午10:35写道：

**Comment by shineforwu** [comment]
嗯好的 博主 谢谢
